apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  template:
    metadata:
      name: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: batch-job
        image: hartej3003/ch4:latest

